Zorbus\GalleryBundle\Entity\Category:
    type: entity
    table: zorbus_gallery_category
    repositoryClass: Zorbus\GalleryBundle\Entity\CategoryRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            nullable: false
        description:
            type: text
            nullable: true
        lang:
            type: string
            length: 5
            nullable: true
            default: en_US
        image:
            type: string
            length: 255
            nullable: true
        enabled:
            type: boolean
            default: true
            nullable: true
        slug:
            type: string
            length: 255
            nullable: true
            gedmo:
                slug:
                    separator: '-'
                    style: default
                    fields:
                        - name
        created_at:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks:
        prePersist: [preImageUpload]
        preUpdate: [preImageUpload]
        postPersist: [postImageUpload]
        postUpdate: [postImageUpload]
        postRemove: [postRemove]
    oneToMany:
        galleries:
            targetEntity: Gallery
            mappedBy: category
            orderBy:
                position: ASC